
BackItems = {
    ["markedbills"] = { -- Item Name
        model="prop_money_bag_01", -- Model you want to display
        back_bone = 24818, -- PED bone the entity is attached to.
        -- Location of the model on the players back. Note this is and offset relative to the players bone coords.
        x = -0.4,
        y = -0.17,
        z = -0.12,
        -- Rotaion of the object.
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },

    ["meth"] = {
        model="hei_prop_pill_bag_01", 
        back_bone = 24818,
        x = -0.1,
        y = -0.17,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },

    ["weapon_smg"] = {
        model="w_sb_smg", 
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 46.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle"] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle_mk2"] = {
        model="w_ar_assaultrifle",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle_mk2"] = {
        model="w_ar_carbinerifle", 
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_rpg"] = {
        model="w_lr_rpg", 
        back_bone = 24818,
        x = 0.2,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ["coke_brick"] = {
        model="bkr_prop_coke_cutblock_01", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 90.0,
    },
    ["weed_bud"] = {
        model="bkr_prop_weed_drying_01a", 
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    -- GGC Weapons -- Melees
    ["weapon_sledgehammer"] = {
        model="w_me_sledgehammer",
        back_bone = 24818,
        x = -0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_katana"] = {
        model="w_me_katana",
        back_bone = 24818,
        x = -0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_keyboard"] = {
        model="w_me_keyboard",
        back_bone = 24818,
        x = -0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    -- GGC Weapons -- SMGs
    ["weapon_pmxfm"] = {
        model="pmx_fluffymods",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 30.0,
        z_rotation = 180.0,
    },
    ["weapon_mac10"] = {
        model="w_sb_mac10",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 30.0,
        z_rotation = 180.0,
    },
    ['weapon_microsmg'] = {
        model = "w_sb_microsmg",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 46.0,
        z_rotation = 180.0,
    },
    ['weapon_smg_mk2'] = {
        model = "w_sb_microsmg",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 46.0,
        z_rotation = 180.0,
    },
    ['weapon_assaultsmg'] = {
        model = "w_sb_assaultsmg",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 46.0,
        z_rotation = 180.0,
    },
    ['weapon_minismg'] = {
        model = "w_sb_microsmg",
        back_bone = 24818,
        x = -0.05,
        y = 0.20,
        z = 0.0,
        x_rotation = 180.0,
        y_rotation = 46.0,
        z_rotation = 180.0,
    },
    -- GGC Weapons -- Rifles
    ["weapon_ak47"] = {
        model="w_ar_ak47",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_ak74"] = {
        model="w_ar_ak74",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_aks74"] = {
        model="w_ar_assaultrifle_aks74",
        back_bone = 24818,
        x =  0.12,
        y = -0.17,
        z = -0.0,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 0.0,
    },
    ["weapon_groza"] = {
        model="w_ar_groza",
        back_bone = 24818,
        x = -0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_m4"] = {
        model="w_ar_m4",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_m6ic"] = {
        model="m6ic",
        back_bone = 24818,
        x =  0.12,
        y = -0.17,
        z = -0.0,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 0.0,
    },
    ["weapon_mk47fm"] = {
        model="MK47FluffysMods",
        back_bone = 24818,
        x = -0.0,
        y = -0.17,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_scarsc"] = {
        model="w_ar_scarsc",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
    ["weapon_scarh"] = {
        model="w_ar_scarh",
        back_bone = 24818,
        x = 0.05,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -30.0,
        z_rotation = 180.0,
    },
}
